# Generated by Django 5.2.6 on 2025-09-09 11:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.CharField()),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('footwear', 'Footwear'), ('apparel', 'Apparel'), ('accessories', 'Accessories'), ('collectibles', 'Collectibles'), ('sneakers', 'Sneakers')], max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
